[2025-10-06T19:28:43.090+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG_completo.chunk_from_txt manual__2025-10-06T19:26:49+00:00 [queued]>
[2025-10-06T19:28:43.093+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG_completo.chunk_from_txt manual__2025-10-06T19:26:49+00:00 [queued]>
[2025-10-06T19:28:43.094+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-06T19:28:43.098+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): chunk_from_txt> on 2025-10-06 19:26:49+00:00
[2025-10-06T19:28:43.106+0000] {standard_task_runner.py:57} INFO - Started process 318 to run task
[2025-10-06T19:28:43.108+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG_completo', 'chunk_from_txt', 'manual__2025-10-06T19:26:49+00:00', '--job-id', '282', '--raw', '--subdir', 'DAGS_FOLDER/Ingestion_pipeline.py', '--cfg-path', '/tmp/tmp5xhqsqtf']
[2025-10-06T19:28:43.111+0000] {standard_task_runner.py:85} INFO - Job 282: Subtask chunk_from_txt
[2025-10-06T19:28:43.134+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG_completo.chunk_from_txt manual__2025-10-06T19:26:49+00:00 [running]> on host a21c1baf7ef9
[2025-10-06T19:28:43.168+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG_completo' AIRFLOW_CTX_TASK_ID='chunk_from_txt' AIRFLOW_CTX_EXECUTION_DATE='2025-10-06T19:26:49+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-06T19:26:49+00:00'
[2025-10-06T19:28:43.169+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-06T19:28:43.170+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-06T19:28:43.170+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-06T19:28:43.170+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-06T19:28:43.170+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-06T19:28:43.344+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-06T19:28:43.345+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-06T19:28:45.998+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/chunk_from_txt_task.py", line 58, in task_chunk_txt
    chunks_map = documents_to_chunks([doc], max_tokens_chunk=max_tokens_chunk, overlap=overlap)
  File "/opt/airflow/plugins/tasks/loader_pdfs.py", line 267, in documents_to_chunks
    def _split_indices(n: int, max_len: int, overlap_len: int) -> list[tuple[int, int]]:
TypeError: 'type' object is not subscriptable
[2025-10-06T19:28:46.004+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG_completo, task_id=chunk_from_txt, execution_date=20251006T192649, start_date=20251006T192843, end_date=20251006T192846
[2025-10-06T19:28:46.011+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 282 for task chunk_from_txt ('type' object is not subscriptable; 318)
[2025-10-06T19:28:46.044+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-06T19:28:46.056+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
