[2025-09-30T14:52:35.534+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:51:56.904611+00:00 [queued]>
[2025-09-30T14:52:35.539+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:51:56.904611+00:00 [queued]>
[2025-09-30T14:52:35.540+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-30T14:52:35.546+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): listar_boletines_minio> on 2025-09-30 14:51:56.904611+00:00
[2025-09-30T14:52:35.549+0000] {standard_task_runner.py:57} INFO - Started process 986 to run task
[2025-09-30T14:52:35.551+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'listar_boletines_minio', 'manual__2025-09-30T14:51:56.904611+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmptycwwq4l']
[2025-09-30T14:52:35.553+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask listar_boletines_minio
[2025-09-30T14:52:35.576+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.listar_boletines_minio manual__2025-09-30T14:51:56.904611+00:00 [running]> on host 536168cd08ce
[2025-09-30T14:52:35.607+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='listar_boletines_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-09-30T14:51:56.904611+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-30T14:51:56.904611+00:00'
[2025-09-30T14:52:35.608+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-30T14:52:35.609+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-09-30T14:52:35.609+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-09-30T14:52:35.609+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-09-30T14:52:35.610+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-09-30T14:52:35.857+0000] {logging_mixin.py:151} INFO - üóÇÔ∏è Listado de PDFs en s3://respaldo2/boletines/2025/:
[2025-09-30T14:52:35.857+0000] {s3.py:1361} INFO - This function shadows the 'download_file' method of S3 API, but it is not the same. If you want to use the original method from S3 API, please call 'S3Hook.get_conn().download_file()'
[2025-09-30T14:52:35.857+0000] {s3.py:1367} INFO - Downloading source S3 file from Bucket respaldo2 with path boletines/2025/22032_2025-09-16.pdf
[2025-09-30T14:52:35.904+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/procesamiento_utils.py", line 68, in leer_y_loguear_minio
    size_bytes = os.path.getsize(local_path)
  File "/usr/local/lib/python3.8/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpxnjh3t4a/22032_2025-09-16.pdf'
[2025-09-30T14:52:35.908+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=listar_boletines_minio, execution_date=20250930T145156, start_date=20250930T145235, end_date=20250930T145235
[2025-09-30T14:52:35.912+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task listar_boletines_minio ([Errno 2] No such file or directory: '/tmp/tmpxnjh3t4a/22032_2025-09-16.pdf'; 986)
[2025-09-30T14:52:35.942+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-30T14:52:35.950+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
