[2025-10-01T15:00:25.561+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.pinecone_upsert manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T15:00:25.565+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.pinecone_upsert manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T15:00:25.565+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-01T15:00:25.570+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): pinecone_upsert> on 2025-10-01 13:33:42.656094+00:00
[2025-10-01T15:00:25.576+0000] {standard_task_runner.py:57} INFO - Started process 5757 to run task
[2025-10-01T15:00:25.578+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'pinecone_upsert', 'manual__2025-10-01T13:33:42.656094+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmpoya_58r7']
[2025-10-01T15:00:25.580+0000] {standard_task_runner.py:85} INFO - Job 65: Subtask pinecone_upsert
[2025-10-01T15:00:25.602+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.pinecone_upsert manual__2025-10-01T13:33:42.656094+00:00 [running]> on host b23249bdd303
[2025-10-01T15:00:25.633+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='pinecone_upsert' AIRFLOW_CTX_EXECUTION_DATE='2025-10-01T13:33:42.656094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-01T13:33:42.656094+00:00'
[2025-10-01T15:00:25.634+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-01T15:00:25.635+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:25.635+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-01T15:00:25.635+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:25.636+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-01T15:00:25.764+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:25.764+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:25.806+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:25.806+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:25.846+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:25.847+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.043+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.043+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.080+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.080+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.120+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.120+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.161+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.161+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.204+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.204+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.252+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.253+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.430+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.430+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.469+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.470+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.508+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T15:00:26.508+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T15:00:26.550+0000] {SentenceTransformer.py:208} INFO - Use pytorch device_name: cpu
[2025-10-01T15:00:26.550+0000] {SentenceTransformer.py:216} INFO - Load pretrained SentenceTransformer: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
[2025-10-01T15:01:18.381+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/pinecone_upsert_task.py", line 15, in task_pinecone_upsert
    out = upsert_vectors_from_ndjson(
  File "/opt/airflow/plugins/tasks/vector_pinecone.py", line 124, in upsert_vectors_from_ndjson
    ensure_index(index_name=index_name, dim=dim, metric="cosine")
  File "/opt/airflow/plugins/tasks/vector_pinecone.py", line 54, in ensure_index
    pc = _pc_client()
  File "/opt/airflow/plugins/tasks/vector_pinecone.py", line 43, in _pc_client
    raise RuntimeError("PINECONE_API_KEY no está definido en el entorno.")
RuntimeError: PINECONE_API_KEY no está definido en el entorno.
[2025-10-01T15:01:18.387+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=pinecone_upsert, execution_date=20251001T133342, start_date=20251001T150025, end_date=20251001T150118
[2025-10-01T15:01:18.393+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 65 for task pinecone_upsert (PINECONE_API_KEY no está definido en el entorno.; 5757)
[2025-10-01T15:01:18.480+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-01T15:01:18.490+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
