[2025-10-01T15:30:10.116+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.pinecone_query_demo manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T15:30:10.120+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.pinecone_query_demo manual__2025-10-01T13:33:42.656094+00:00 [queued]>
[2025-10-01T15:30:10.120+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-01T15:30:10.125+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): pinecone_query_demo> on 2025-10-01 13:33:42.656094+00:00
[2025-10-01T15:30:10.131+0000] {standard_task_runner.py:57} INFO - Started process 440 to run task
[2025-10-01T15:30:10.134+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'pinecone_query_demo', 'manual__2025-10-01T13:33:42.656094+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmp4cikmt9g']
[2025-10-01T15:30:10.136+0000] {standard_task_runner.py:85} INFO - Job 74: Subtask pinecone_query_demo
[2025-10-01T15:30:10.156+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.pinecone_query_demo manual__2025-10-01T13:33:42.656094+00:00 [running]> on host 2f9c2b1ff132
[2025-10-01T15:30:10.174+0000] {abstractoperator.py:709} ERROR - Exception rendering Jinja template for task 'pinecone_query_demo', field 'op_kwargs'. Template: {'index_name': 'boletines-2025', 'namespace': '2025', 'query': '{{ params.eval_query }}', 'top_k': 5, 'model_name': 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 169, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 169, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 157, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 114, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'eval_query'
[2025-10-01T15:30:10.177+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1516, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1645, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2283, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1245, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 701, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 169, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 169, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 157, in render_template
    return self._render(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 655, in _render
    return super()._render(template, context, dag=dag)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 114, in _render
    return render_template_to_string(template, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 289, in render_template_to_string
    return render_template(template, cast(MutableMapping[str, Any], context), native=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/helpers.py", line 284, in render_template
    return "".join(nodes)
  File "<template>", line 12, in root
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/runtime.py", line 852, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'eval_query'
[2025-10-01T15:30:10.182+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=pinecone_query_demo, execution_date=20251001T133342, start_date=20251001T153010, end_date=20251001T153010
[2025-10-01T15:30:10.185+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 74 for task pinecone_query_demo ('dict object' has no attribute 'eval_query'; 440)
[2025-10-01T15:30:10.230+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-01T15:30:10.238+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
