[2025-09-30T19:52:50.941+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.chunk_from_txt manual__2025-09-30T19:13:02.728529+00:00 [queued]>
[2025-09-30T19:52:50.945+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.chunk_from_txt manual__2025-09-30T19:13:02.728529+00:00 [queued]>
[2025-09-30T19:52:50.946+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-09-30T19:52:50.951+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): chunk_from_txt> on 2025-09-30 19:13:02.728529+00:00
[2025-09-30T19:52:50.955+0000] {standard_task_runner.py:57} INFO - Started process 2419 to run task
[2025-09-30T19:52:50.957+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'chunk_from_txt', 'manual__2025-09-30T19:13:02.728529+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmpya9yfa01']
[2025-09-30T19:52:50.959+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask chunk_from_txt
[2025-09-30T19:52:50.983+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.chunk_from_txt manual__2025-09-30T19:13:02.728529+00:00 [running]> on host b23249bdd303
[2025-09-30T19:52:51.015+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='chunk_from_txt' AIRFLOW_CTX_EXECUTION_DATE='2025-09-30T19:13:02.728529+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-30T19:13:02.728529+00:00'
[2025-09-30T19:52:51.018+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-09-30T19:52:51.018+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-09-30T19:52:51.019+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-09-30T19:52:51.019+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-09-30T19:52:51.019+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-09-30T19:52:51.351+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/chunk_from_txt_task.py", line 46, in task_chunk_txt
    text = read_text(bucket=bucket_name, key=key, aws_conn_id=aws_conn_id)
  File "/opt/airflow/plugins/tasks/s3_utilities.py", line 157, in read_text
    return hook.read_key(key=key, bucket_name=bucket, encoding=encoding)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 123, in wrapper
    bound_args = function_signature.bind(*args, **kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3037, in bind
    return self._bind(args, kwargs)
  File "/usr/local/lib/python3.8/inspect.py", line 3026, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'encoding'
[2025-09-30T19:52:51.356+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=chunk_from_txt, execution_date=20250930T191302, start_date=20250930T195250, end_date=20250930T195251
[2025-09-30T19:52:51.360+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 33 for task chunk_from_txt (got an unexpected keyword argument 'encoding'; 2419)
[2025-09-30T19:52:51.395+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-09-30T19:52:51.404+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
