[2025-10-01T18:22:25.187+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flujo_RAG.eval_fusion manual__2025-10-01T18:20:14+00:00 [queued]>
[2025-10-01T18:22:25.191+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flujo_RAG.eval_fusion manual__2025-10-01T18:20:14+00:00 [queued]>
[2025-10-01T18:22:25.191+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-01T18:22:25.195+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): eval_fusion> on 2025-10-01 18:20:14+00:00
[2025-10-01T18:22:25.202+0000] {standard_task_runner.py:57} INFO - Started process 8903 to run task
[2025-10-01T18:22:25.205+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'flujo_RAG', 'eval_fusion', 'manual__2025-10-01T18:20:14+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/RAG_dag.py', '--cfg-path', '/tmp/tmph50wdv9l']
[2025-10-01T18:22:25.207+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask eval_fusion
[2025-10-01T18:22:25.229+0000] {task_command.py:415} INFO - Running <TaskInstance: flujo_RAG.eval_fusion manual__2025-10-01T18:20:14+00:00 [running]> on host 2f9c2b1ff132
[2025-10-01T18:22:25.263+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flujo_RAG' AIRFLOW_CTX_TASK_ID='eval_fusion' AIRFLOW_CTX_EXECUTION_DATE='2025-10-01T18:20:14+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-01T18:20:14+00:00'
[2025-10-01T18:22:25.264+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-10-01T18:22:25.265+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T18:22:25.265+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: AWS Connection (conn_id='minio_s3', conn_type='s3') has connection type 's3', which has been replaced by connection type 'aws'. Please update your connection to have `conn_type='aws'`.

[2025-10-01T18:22:25.265+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T18:22:25.266+0000] {warnings.py:109} WARNING - <string>:8: AirflowProviderDeprecationWarning: Host minio specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-10-01T18:22:25.311+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T18:22:25.312+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T18:22:25.445+0000] {logging_mixin.py:151} INFO - üìù Evaluando fusi√≥n: s3://respaldo2/rag/fusion/2025/fusion_contrataci_n_p_blica_vial_20251001_182223.json
[2025-10-01T18:22:25.446+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T18:22:25.446+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T18:22:25.487+0000] {base.py:73} INFO - Using connection ID 'minio_s3' for task execution.
[2025-10-01T18:22:25.487+0000] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='minio_s3', conn_type='s3') credentials retrieved from login and password.
[2025-10-01T18:22:25.692+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/plugins/tasks/eval_fusion_task.py", line 96, in task_eval_fusion
    qrels = IO.load_qrels(local_qrels)  # dict: {query_text: {doc_id: rel, ...}, ...}
AttributeError: module 'tasks.io_utils' has no attribute 'load_qrels'
[2025-10-01T18:22:25.697+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=flujo_RAG, task_id=eval_fusion, execution_date=20251001T182014, start_date=20251001T182225, end_date=20251001T182225
[2025-10-01T18:22:25.702+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task eval_fusion (module 'tasks.io_utils' has no attribute 'load_qrels'; 8903)
[2025-10-01T18:22:25.739+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-01T18:22:25.747+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
